const accessList = [
  {
    phone: '2125559876',
    address1: '456 Park Avenue',
    address2: 'Unit 22E',
    city: 'New York',
    state: 'New York',
    zip: '10022',
    accessCode: 6789,
    emergencyContactName: 'Michael Lee',
    emergencyContactPhone: '6465554321',
    wifi: 'NYCWiFi456',
    additionalNotes:
      'My two dogs, Max and Bella, need to be walked twice a day and fed once in the morning. They are both friendly and love to play fetch. Please make sure they have plenty of water and are not left alone for more than 6 hours. Thank you!',
    userId: 1,
  },
  {
    phone: '3475551111',
    address1: '789 Broadway',
    address2: 'Apt 3D',
    city: 'New York',
    state: 'New York',
    zip: '10003',
    accessCode: 1234,
    emergencyContactName: 'Jennifer Smith',
    emergencyContactPhone: '6465552222',
    wifi: 'NYCWiFi789',
    additionalNotes:
      'My dog, Luna, needs to be fed twice a day. She is shy at first but loves to play with toys once she gets to know you. Thank you for taking care of her!',
    userId: 2,
  },
  {
    phone: '2125553333',
    address1: '234 Park Place',
    address2: 'Apt 4F',
    city: 'Brooklyn',
    state: 'New York',
    zip: '11238',
    accessCode: 5678,
    emergencyContactName: 'Karen Johnson',
    emergencyContactPhone: '9175554444',
    wifi: 'NYCWiFi234',
    additionalNotes:
      'My dog, Charlie, needs to be walked three times a day and fed twice a day. He is friendly with people but may bark at other dogs. Please keep him on a leash at all times. Thank you!',
    userId: 3,
  },
  {
    phone: '6465555555',
    address1: '321 Hudson Street',
    address2: 'Apt 2A',
    city: 'New York',
    state: 'New York',
    zip: '10013',
    accessCode: 9012,
    emergencyContactName: 'David Rodriguez',
    emergencyContactPhone: '2125556666',
    wifi: 'NYCWiFi321',
    additionalNotes:
      'My two dogs, Simba and Nala, need to be fed twice a day. They are both very friendly and love to cuddle. Thank you for taking care of them!',
    userId: 4,
  },
  {
    phone: '7049748941',
    address1: '50853 Weeping Birch Plaza',
    address2: '1',
    city: 'Charlotte',
    state: 'North Carolina',
    zip: '28205',
    accessCode: 3331,
    emergencyContactName: 'Winny Hof',
    emergencyContactPhone: '3787028510',
    wifi: 'mKS98DOL',
    additionalNotes:
      'Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
    userId: 5,
  },
  {
    phone: '2511057085',
    address1: '38 Truax Lane',
    address2: null,
    city: 'Mobile',
    state: 'Alabama',
    zip: '36689',
    accessCode: 5567,
    emergencyContactName: 'Rivi Scapens',
    emergencyContactPhone: '3546057579',
    wifi: 'g3e2jK',
    additionalNotes:
      'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.',
    userId: 6,
  },
  {
    phone: '7185557777',
    address1: '567 Fifth Avenue',
    address2: 'Apt 12B',
    city: 'Brooklyn',
    state: 'New York',
    zip: '11215',
    accessCode: 3456,
    emergencyContactName: 'Andrew Huberman',
    emergencyContactPhone: '9175558888',
    wifi: 'NYCWiFi567',
    additionalNotes:
      'My dog, Max, needs to be walked twice a day and fed once in the morning. He is friendly with people and other dogs. Please make sure he has plenty of water and is not left alone for more than 4 hours. Thank you!',
    userId: 7,
  },
  {
    phone: '7185551234',
    address1: '100 Main Street',
    address2: null,
    city: 'Brooklyn',
    state: 'New York',
    zip: '11201',
    accessCode: 4321,
    emergencyContactName: 'Sophia Smith',
    emergencyContactPhone: '3475556789',
    wifi: 'BrooklynWiFi123',
    additionalNotes:
      'My dog, Whiskers, needs to be fed twice a day. She is very friendly and loves to play with string toys. Please also water my plants every other day. Thank you!',
    userId: 8,
  },
  {
    phone: '9175559876',
    address1: '789 Park Place',
    address2: 'Apt 3B',
    city: 'New York',
    state: 'New York',
    zip: '10016',
    accessCode: 2345,
    emergencyContactName: 'Samantha Smith',
    emergencyContactPhone: '2125555678',
    wifi: 'ManhattanWiFi789',
    additionalNotes:
      'My dog, Charlie, needs to be walked three times a day and fed twice a day. He is very energetic and loves to play with balls. Please also give him his medication with his breakfast. Thank you!',
    userId: 9,
  },
  {
    phone: '6465552345',
    address1: '321 West End Avenue',
    address2: 'Unit 5C',
    city: 'New York',
    state: 'New York',
    zip: '10023',
    accessCode: 9876,
    emergencyContactName: 'William Wong',
    emergencyContactPhone: '7185556789',
    wifi: 'UpperWestWiFi321',
    additionalNotes:
      'My two dogs, Luna and Simba, need to be fed twice a day. Luna is shy at first but will warm up to you if you play with her using feather toys. Simba is very friendly and loves to be petted. Please also water my plants every day. Thank you!',
    userId: 10,
  },
  {
    phone: '2125555678',
    address1: '456 Lexington Avenue',
    address2: 'Suite 1200',
    city: 'New York',
    state: 'New York',
    zip: '10017',
    accessCode: 3456,
    emergencyContactName: 'David Chen',
    emergencyContactPhone: '6465557890',
    wifi: 'MidtownWiFi456',
    additionalNotes:
      'My dog, Ginger, needs to be fed once a day. She is very active and loves to run on her wheel. Please also water my plants every other day. Thank you!',
    userId: 11,
  },
  {
    phone: '9175552345',
    address1: '101 5th Avenue',
    address2: 'Apt 2A',
    city: 'New York',
    state: 'New York',
    zip: '10003',
    accessCode: 7890,
    emergencyContactName: 'Emily Jones',
    emergencyContactPhone: '7185551234',
    wifi: 'UnionSquareWiFi101',
    additionalNotes:
      'My dog, Whiskers, needs to be fed twice a day. She is very friendly and loves to play with string toys. Please also water my plants every other day. Thank you!',
    userId: 12,
  },
  {
    phone: '9175553456',
    address1: '789 3rd Avenue',
    address2: 'Apt 3B',
    city: 'New York',
    state: 'New York',
    zip: '10017',
    accessCode: 6789,
    emergencyContactName: 'Samantha Smith',
    emergencyContactPhone: '2125555678',
    wifi: 'MidtownWiFi789',
    additionalNotes:
      'My dog, Charlie, needs to be walked three times a day and fed twice a day. He is very energetic and loves to play with balls. Please also give him his medication with his breakfast. Thank you!',
    userId: 13,
  },
  {
    phone: '7185552345',
    address1: '456 Broadway',
    address2: 'Suite 5A',
    city: 'New York',
    state: 'New York',
    zip: '10013',
    accessCode: 4567,
    emergencyContactName: 'David Kim',
    emergencyContactPhone: '6465557890',
    wifi: 'TribecaWiFi456',
    additionalNotes:
      'My dog, Ginger, needs to be fed once a day. She is very active. Please also water my plants every other day. Thank you!',
    userId: 14,
  },

  {
    phone: '2125553456',
    address1: '789 Park Ave',
    address2: 'Floor 8',
    city: 'New York',
    state: 'New York',
    zip: '10021',
    accessCode: 7890,
    emergencyContactName: 'John Williams',
    emergencyContactPhone: '9175555678',
    wifi: 'UESWiFi789',
    additionalNotes:
      'My dog, Buddy, needs to be walked four times a day and fed twice a day. He is a friendly dog who loves to play fetch. Please also make sure he has plenty of water. Thank you!',
    userId: 15,
  },

  {
    phone: '2125113456',
    address1: '789 Park Ave',
    address2: 'Floor 8',
    city: 'New York',
    state: 'New York',
    zip: '10021',
    accessCode: 7890,
    emergencyContactName: 'John Williams',
    emergencyContactPhone: '9175555678',
    wifi: 'UESWiFi789',
    additionalNotes:
      'My dog, Buddy, needs to be walked four times a day and fed twice a day. He is a friendly dog who loves to play fetch. Please also make sure he has plenty of water. Thank you!',
    userId: 16,
  },

  {
    phone: '2125543456',
    address1: '789 Park Ave',
    address2: 'Floor 8',
    city: 'New York',
    state: 'New York',
    zip: '10021',
    accessCode: 7890,
    emergencyContactName: 'John Williams',
    emergencyContactPhone: '9175555678',
    wifi: 'UESWiFi789',
    additionalNotes:
      'My dog, Buddy, needs to be walked four times a day and fed twice a day. He is a friendly dog who loves to play fetch. Please also make sure he has plenty of water. Thank you!',
    userId: 17,
  },

  {
    phone: '2124443456',
    address1: '789 Park Ave',
    address2: 'Floor 8',
    city: 'New York',
    state: 'New York',
    zip: '10021',
    accessCode: 7890,
    emergencyContactName: 'John Williams',
    emergencyContactPhone: '9175555678',
    wifi: 'UESWiFi789',
    additionalNotes:
      'My dog, Buddy, needs to be walked four times a day and fed twice a day. He is a friendly dog who loves to play fetch. Please also make sure he has plenty of water. Thank you!',
    userId: 18,
  },

  {
    phone: '2125553413',
    address1: '789 Park Ave',
    address2: 'Floor 8',
    city: 'New York',
    state: 'New York',
    zip: '10021',
    accessCode: 7890,
    emergencyContactName: 'John Williams',
    emergencyContactPhone: '9175555678',
    wifi: 'UESWiFi789',
    additionalNotes:
      'My dog, Buddy, needs to be walked four times a day and fed twice a day. He is a friendly dog who loves to play fetch. Please also make sure he has plenty of water. Thank you!',
    userId: 19,
  },

  {
    phone: '2125553412',
    address1: '789 Park Ave',
    address2: 'Floor 8',
    city: 'New York',
    state: 'New York',
    zip: '10021',
    accessCode: 7890,
    emergencyContactName: 'John Williams',
    emergencyContactPhone: '9175555678',
    wifi: 'UESWiFi789',
    additionalNotes:
      'My dog, Buddy, needs to be walked four times a day and fed twice a day. He is a friendly dog who loves to play fetch. Please also make sure he has plenty of water. Thank you!',
    userId: 20,
  },
];

module.exports = accessList;
