const favGroups = [];

const favSitters = [
  { userId: 11, sitterId: 3 },
  { userId: 19, sitterId: 10 },
  { userId: 38, sitterId: 3 },
  { userId: 40, sitterId: 4 },
  { userId: 2, sitterId: 1 },
  { userId: 30, sitterId: 9 },
  { userId: 37, sitterId: 7 },
  { userId: 8, sitterId: 10 },
  { userId: 26, sitterId: 7 },
  { userId: 20, sitterId: 10 },
  { userId: 31, sitterId: 9 },
  { userId: 32, sitterId: 9 },
  { userId: 47, sitterId: 10 },
  { userId: 1, sitterId: 1 },
  { userId: 47, sitterId: 11 },
  { userId: 41, sitterId: 1 },
  { userId: 15, sitterId: 4 },
  { userId: 16, sitterId: 9 },

  { userId: 5, sitterId: 2 },
  { userId: 7, sitterId: 11 },
  { userId: 7, sitterId: 8 },
  { userId: 14, sitterId: 9 },
  { userId: 26, sitterId: 4 },
  { userId: 34, sitterId: 11 },
  { userId: 17, sitterId: 2 },
  { userId: 46, sitterId: 6 },
  { userId: 28, sitterId: 8 },
  { userId: 23, sitterId: 4 },
  { userId: 15, sitterId: 7 },
  { userId: 41, sitterId: 5 },
  { userId: 1, sitterId: 4 },
  { userId: 42, sitterId: 1 },
  { userId: 37, sitterId: 6 },
  { userId: 36, sitterId: 10 },
  { userId: 8, sitterId: 9 },
  { userId: 10, sitterId: 3 },
  { userId: 46, sitterId: 1 },
  { userId: 50, sitterId: 11 },
  { userId: 44, sitterId: 8 },
  { userId: 40, sitterId: 10 },
  { userId: 17, sitterId: 1 },
  { userId: 10, sitterId: 2 },
  { userId: 21, sitterId: 6 },
  { userId: 30, sitterId: 2 },
  { userId: 29, sitterId: 11 },
  { userId: 15, sitterId: 2 },
  { userId: 4, sitterId: 8 },
  { userId: 11, sitterId: 2 },
];

module.exports = { favGroups, favSitters };
