const favGroups = [];

const favSitters = [
  { userId: 11, sitterId: 3 },
  { userId: 19, sitterId: 10 },
  { userId: 18, sitterId: 3 },
  { userId: 20, sitterId: 4 },
  { userId: 2, sitterId: 1 },
  { userId: 10, sitterId: 9 },
  { userId: 17, sitterId: 7 },
  { userId: 8, sitterId: 10 },
  { userId: 16, sitterId: 7 },
  { userId: 20, sitterId: 10 },
  { userId: 11, sitterId: 9 },
  { userId: 12, sitterId: 9 },
  { userId: 17, sitterId: 10 },
  { userId: 1, sitterId: 1 },
  { userId: 17, sitterId: 11 },
  { userId: 11, sitterId: 1 },
  { userId: 15, sitterId: 4 },
  { userId: 16, sitterId: 9 },
  { userId: 5, sitterId: 2 },
  { userId: 7, sitterId: 11 },
  { userId: 7, sitterId: 8 },
  { userId: 14, sitterId: 9 },
  { userId: 16, sitterId: 4 },
  { userId: 14, sitterId: 11 },
  { userId: 17, sitterId: 2 },
  { userId: 16, sitterId: 6 },
  { userId: 18, sitterId: 8 },
  { userId: 13, sitterId: 4 },
  { userId: 15, sitterId: 7 },
  { userId: 11, sitterId: 5 },
  { userId: 1, sitterId: 4 },
  { userId: 12, sitterId: 1 },
  { userId: 17, sitterId: 6 },
  { userId: 16, sitterId: 10 },
  { userId: 8, sitterId: 9 },
  { userId: 10, sitterId: 3 },
  { userId: 416, sitterId: 1 },
  { userId: 10, sitterId: 11 },
  { userId: 14, sitterId: 8 },
  { userId: 10, sitterId: 10 },
  { userId: 17, sitterId: 1 },
  { userId: 10, sitterId: 2 },
  { userId: 11, sitterId: 6 },
  { userId: 10, sitterId: 2 },
  { userId: 19, sitterId: 11 },
  { userId: 15, sitterId: 2 },
  { userId: 4, sitterId: 8 },
  { userId: 11, sitterId: 2 },
];

module.exports = { favGroups, favSitters };
