const pet_details = [
  {
    about: 'Very friendly and loves to cuddle',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'medium',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats dry food with wet food as a topper',
    walkSchedule: '3+',
    walkDuration: '45',
    walkDetails: 'Enjoys walks in the park',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '2-4 hours',
    canBeLeftAloneDetails: 'Fine with being left alone for short periods',
    additionalDetails: 'Loves playing fetch',
    vetInfo: '',
    petId: 1,
  },
  {
    about: 'Shy at first but very affectionate',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'yes',
    energyLevels: 'low',
    feedingSchedule: 'three times a day',
    foodDetails: 'Eats prescription food for sensitive stomach',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Prefers short walks in quiet areas',
    medications: 'oral',
    medicationDetails: 'Takes medication for anxiety',
    canBeLeftAlone: '4-6 hours',
    canBeLeftAloneDetails: 'Needs some time to adjust to being left alone',
    additionalDetails: 'Enjoys snuggling on the couch',
    vetInfo: '',
    petId: 2,
  },
  {
    about: 'Playful and loves to run',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'no',
    energyLevels: 'high',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a high-protein diet',
    walkSchedule: '4+',
    walkDuration: '60',
    walkDetails: 'Needs long walks and runs to burn energy',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-2 hours',
    canBeLeftAloneDetails: 'Does not like being left alone for long',
    additionalDetails: 'Loves chasing balls',
    vetInfo: '',
    petId: 3,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'medium',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a grain-free diet',
    walkSchedule: '2-3',
    walkDuration: '45',
    walkDetails: 'Enjoys walking in the park and socializing with other dogs',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '3-4 hours',
    canBeLeftAloneDetails: 'Adjusts well to being left alone',
    additionalDetails: 'Loves cuddling and playing with toys',
    vetInfo: '',
    petId: 4,
  },
  {
    about: 'Calm and well-behaved',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'low',
    feedingSchedule: 'once a day',
    foodDetails: 'Eats a special diet for weight management',
    walkSchedule: '1-2',
    walkDuration: '20',
    walkDetails: 'Prefers short walks in quiet areas',
    medications: 'oral',
    medicationDetails: 'Takes medication for arthritis',
    canBeLeftAlone: '4-5 hours',
    canBeLeftAloneDetails: 'Comfortable being left alone for a few hours',
    additionalDetails: 'Loves napping and lounging in the sun',
    vetInfo: '',
    petId: 5,
  },
  {
    about: 'Loves attention and cuddles',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'medium',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats grain-free food',
    walkSchedule: '2',
    walkDuration: '45',
    walkDetails: 'Enjoys walks in the park',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '4-5 hours',
    canBeLeftAloneDetails: 'Does well being left alone for a few hours',
    additionalDetails: 'Loves playing with toys',
    vetInfo: '',
    petId: 6,
  },
  {
    about: 'Very active and loves to play fetch',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'high',
    feedingSchedule: 'three times a day',
    foodDetails: 'Eats a raw food diet',
    walkSchedule: '4+',
    walkDuration: '60',
    walkDetails: 'Needs long walks and runs to burn energy',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '3-4 hours',
    canBeLeftAloneDetails: 'Does well being left alone for a few hours',
    additionalDetails: 'Loves swimming in the pool',
    vetInfo: '',
    petId: 7,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'yes',
    energyLevels: 'medium',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Enjoys walks in quiet areas',
    medications: 'oral',
    medicationDetails: 'Takes medication for arthritis',
    canBeLeftAlone: '6-8 hours',
    canBeLeftAloneDetails: 'Can handle being left alone for a workday',
    additionalDetails: 'Loves belly rubs',
    vetInfo: '',
    petId: 8,
  },
  {
    about: 'Loyal and obedient',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: false,
    reactivity: 'No',
    friendlyWithDogs: 'no',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats grain-free kibble',
    walkSchedule: '3',
    walkDuration: '45',
    walkDetails: 'Likes to explore new areas',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '6-8 hours',
    canBeLeftAloneDetails: 'Used to being left alone',
    additionalDetails: 'Enjoys playing fetch',
    vetInfo: '',
    petId: 9,
  },
  {
    about: 'Calm and cuddly',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'low',
    feedingSchedule: 'three times a day',
    foodDetails: 'Eats wet food only',
    walkSchedule: '1',
    walkDuration: '20',
    walkDetails: 'Prefers short walks around the block',
    medications: 'oral',
    medicationDetails: 'Takes medication for arthritis',
    canBeLeftAlone: '2-4 hours',
    canBeLeftAloneDetails: 'Needs some company while left alone',
    additionalDetails: 'Loves belly rubs',
    vetInfo: '',
    petId: 10,
  },
  {
    about: 'Active and adventurous',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'no',
    energyLevels: 'high',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a raw food diet',
    walkSchedule: '2',
    walkDuration: '60',
    walkDetails: 'Enjoys long hikes in the mountains',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '4-6 hours',
    canBeLeftAloneDetails: 'Needs plenty of exercise before being left alone',
    additionalDetails: 'Loves to swim',
    vetInfo: '',
    petId: 11,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Likes to stop and smell the flowers',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '2-4 hours',
    canBeLeftAloneDetails:
      'Does not like being left alone for long periods of time',
    additionalDetails: 'Loves to play with toys',
    vetInfo: '',
    petId: 12,
  },
  {
    about: 'Shy and reserved',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'High',
    friendlyWithDogs: 'no',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'no',
    energyLevels: 'low',
    feedingSchedule: 'once a day',
    foodDetails: 'Eats dry food only',
    walkSchedule: '1',
    walkDuration: '15',
    walkDetails: 'Likes short walks around the neighborhood',
    medications: 'oral',
    medicationDetails: 'Takes medication for anxiety',
    canBeLeftAlone: '1-2 hours',
    canBeLeftAloneDetails: 'Needs a calm environment when left alone',
    additionalDetails: 'Loves to snuggle in blankets',
    vetInfo: '',
    petId: 13,
  },
  {
    about: 'Energetic and curious',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: false,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'high',
    feedingSchedule: 'three times a day',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '3',
    walkDuration: '30',
    walkDetails: 'Loves to explore new areas and meet new people',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '4-6 hours',
    canBeLeftAloneDetails:
      'Needs plenty of toys to keep occupied when left alone',
    additionalDetails: 'Loves to play fetch and chase',
    vetInfo: '',
    petId: 14,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Loves to sniff and explore during walks',
    medications: 'none',
    medicationDetails: 'no medication',
    canBeLeftAlone: '2-4 hours',
    canBeLeftAloneDetails:
      'Does well when left alone for short periods of time',
    additionalDetails: 'Enjoys playing with toys and cuddling',
    vetInfo: 'Up-to-date on all vaccinations',
    petId: 15,
  },
];

module.exports = pet_details;
