const pet_details = [
  {
    about: 'Very friendly and loves to cuddle',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats dry food with wet food as a topper',
    walkSchedule: '3',
    walkDuration: '30',
    walkDetails: 'Enjoys walks in the park',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails: 'Fine with being left alone for short periods',
    additionalDetails: 'Loves playing fetch',

    petId: 1,
  },
  {
    about: 'Shy at first but very affectionate',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'yes',
    energyLevels: 'low',
    feedingSchedule: 'custom',
    foodDetails: 'Eats prescription food for sensitive stomach',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Prefers short walks in quiet areas',
    medications: 'pill',
    medicationDetails: 'Takes medication for anxiety',
    canBeLeftAlone: 'custom',
    canBeLeftAloneDetails: 'Needs some time to adjust to being left alone',
    additionalDetails: 'Enjoys snuggling on the couch',

    petId: 2,
  },
  {
    about: 'Playful and loves to run',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'no',
    energyLevels: 'high',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a high-protein diet',
    walkSchedule: '4+',
    walkDuration: '60',
    walkDetails: 'Needs long walks and runs to burn energy',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails: 'Does not like being left alone for long',
    additionalDetails: 'Loves chasing balls',
    petId: 3,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a grain-free diet',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Enjoys walking in the park and socializing with other dogs',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails: 'Adjusts well to being left alone',
    additionalDetails: 'Loves cuddling and playing with toys',

    petId: 4,
  },
  {
    about: 'Calm and well-behaved',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'low',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a special diet for weight management',
    walkSchedule: '1',
    walkDuration: '30',
    walkDetails: 'Prefers short walks in quiet areas',
    medications: 'pill',
    medicationDetails: 'Takes medication for arthritis',
    canBeLeftAlone: 'custom',
    canBeLeftAloneDetails: 'Comfortable being left alone for a few hours',
    additionalDetails: 'Loves napping and lounging in the sun',

    petId: 5,
  },
  {
    about: 'Loves attention and cuddles',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'unsure',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats grain-free food',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Enjoys walks in the park',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '<1 hour',
    canBeLeftAloneDetails: 'Does well being left alone for a few hours',
    additionalDetails: 'Loves playing with toys',

    petId: 6,
  },
  {
    about: 'Very active and loves to play fetch',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'high',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a raw food diet',
    walkSchedule: '4+',
    walkDuration: '60',
    walkDetails: 'Needs long walks and runs to burn energy',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails: 'Does well being left alone for a few hours',
    additionalDetails: 'Loves swimming in the pool',

    petId: 7,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Enjoys walks in quiet areas',
    medications: 'pill',
    medicationDetails: 'Takes medication for arthritis',
    canBeLeftAlone: '<1 hour',
    canBeLeftAloneDetails: 'Can handle being left alone for a workday',
    additionalDetails: 'Loves belly rubs',

    petId: 8,
  },
  {
    about: 'Loyal and obedient',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: false,
    reactivity: 'No',
    friendlyWithDogs: 'no',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats grain-free kibble',
    walkSchedule: '3',
    walkDuration: '30',
    walkDetails: 'Likes to explore new areas',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails: 'Used to being left alone',
    additionalDetails: 'Enjoys playing fetch',

    petId: 9,
  },
  {
    about: 'Calm and cuddly',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'low',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats wet food only',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Prefers short walks around the block',
    medications: 'pill',
    medicationDetails: 'Takes medication for arthritis',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails: 'Needs some company while left alone',
    additionalDetails: 'Loves belly rubs',

    petId: 10,
  },
  {
    about: 'Active and adventurous',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'no',
    energyLevels: 'high',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a raw food diet',
    walkSchedule: '2',
    walkDuration: '60',
    walkDetails: 'Enjoys long hikes in the mountains',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: 'custom',
    canBeLeftAloneDetails: 'Needs plenty of exercise before being left alone',
    additionalDetails: 'Loves to swim',

    petId: 11,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '2',
    walkDuration: '30',
    walkDetails: 'Likes to stop and smell the flowers',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails:
      'Does not like being left alone for long periods of time',
    additionalDetails: 'Loves to play with toys',

    petId: 12,
  },
  {
    about: 'Shy and reserved',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'High',
    friendlyWithDogs: 'no',
    friendlyWithCats: 'no',
    friendlyWithChildren: 'no',
    energyLevels: 'low',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats dry food only',
    walkSchedule: '1',
    walkDuration: '15',
    walkDetails: 'Likes short walks around the neighborhood',
    medications: 'pill',
    medicationDetails: 'Takes medication for anxiety',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails: 'Needs a calm environment when left alone',
    additionalDetails: 'Loves to snuggle in blankets',

    petId: 13,
  },
  {
    about: 'Energetic and curious',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: false,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'high',
    feedingSchedule: 'morning',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '3',
    walkDuration: '30',
    walkDetails: 'Loves to explore new areas and meet new people',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails:
      'Needs plenty of toys to keep occupied when left alone',
    additionalDetails: 'Loves to play fetch and chase',

    petId: 14,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '2',
    walkDuration: '60',
    walkDetails: 'Loves to sniff and explore during walks',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails:
      'Does well when left alone for short periods of time',
    additionalDetails: 'Enjoys playing with toys and cuddling',
    vetInfo: 'Up-to-date on all vaccinations',
    petId: 15,
  },
  {
    about: 'Affectionate and playful',
    microchipped: true,
    housetrained: true,
    cratetrained: 'no',
    spayedOrNeutered: true,
    reactivity: 'Low',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a mix of dry and wet food',
    walkSchedule: '2',
    walkDuration: '60',
    walkDetails: 'Loves to sniff and explore during walks',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails:
      'Does well when left alone for short periods of time',
    additionalDetails: 'Enjoys playing with toys and cuddling',
    vetInfo: 'Up-to-date on all vaccinations',
    petId: 16,
  },
  {
    about: 'Very friendly and loves to cuddle',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'moderate',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats dry food with wet food as a topper',
    walkSchedule: '3',
    walkDuration: '30',
    walkDetails: 'Enjoys walks in the park',
    medications: 'n/a',
    medicationDetails: 'no medication',
    canBeLeftAlone: '1-4 hours',
    canBeLeftAloneDetails: 'Fine with being left alone for short periods',
    additionalDetails: 'Loves playing fetch',
    petId: 17,
  },
  {
    about: 'Calm and well-behaved',
    microchipped: true,
    housetrained: true,
    cratetrained: 'yes',
    spayedOrNeutered: true,
    reactivity: 'No',
    friendlyWithDogs: 'yes',
    friendlyWithCats: 'yes',
    friendlyWithChildren: 'yes',
    energyLevels: 'low',
    feedingSchedule: 'twice a day',
    foodDetails: 'Eats a special diet for weight management',
    walkSchedule: '1',
    walkDuration: '30',
    walkDetails: 'Prefers short walks in quiet areas',
    medications: 'pill',
    medicationDetails: 'Takes medication for arthritis',
    canBeLeftAlone: 'custom',
    canBeLeftAloneDetails: 'Comfortable being left alone for a few hours',
    additionalDetails: 'Loves napping and lounging in the sun',

    petId: 18,
  },
];

module.exports = pet_details;
