const pets = [
  {
    name: 'Frank',
    breed: 'American Eskimo Dogs',
    age: 13,
    size: 'extra-large',
    sex: 'female',
    imageSrc: '',
    userId: 1,
  },
  {
    name: 'Rufus',
    breed: 'Silky Terriers',
    age: 3,
    size: 'large',
    sex: 'male',
    imageSrc: '',
    userId: 2,
  },
  {
    name: 'Buddy',
    breed: 'Bearded Collies',
    age: 5,
    size: 'large',
    sex: 'male',
    imageSrc: '',
    userId: 1,
  },
  {
    name: 'Lola',
    breed: 'Silky Terriers',
    age: 7,
    size: 'small',
    sex: 'female',
    imageSrc: '',
    userId: 2,
  },
  {
    name: 'Max',
    breed: 'Belgian Sheepdogs',
    age: 4,
    size: 'medium',
    sex: 'male',
    imageSrc: '',
    userId: 3,
  },
  {
    name: 'Bailey',
    breed: 'Parson Russell Terriers',

    age: 2,
    size: 'large',
    sex: 'female',
    imageSrc: '',
    userId: 4,
  },
  {
    name: 'Charlie',
    breed: 'Parson Russell Terriers',
    age: 6,
    size: 'extra-large',
    sex: 'male',
    imageSrc: '',
    userId: 5,
  },
  {
    name: 'Daisy',
    breed: 'Silky Terriers',
    age: 1,
    size: 'small',
    sex: 'female',
    imageSrc: '',
    userId: 6,
  },
  {
    name: 'Rocky',
    breed: 'Shih Tzu',
    age: 9,
    size: 'large',
    sex: 'male',
    imageSrc: '',
    userId: 7,
  },
  {
    name: 'Maggie',
    breed: 'Bernese Mountain Dogs',
    age: 8,
    size: 'medium',
    sex: 'female',
    imageSrc: '',
    userId: 8,
  },
  {
    name: 'Toby',
    breed: 'Salukis',
    age: 5,
    size: 'small',
    sex: 'male',
    imageSrc: '',
    userId: 9,
  },
  {
    name: 'Molly',
    breed: 'Pulik',
    age: 4,
    size: 'medium',
    sex: 'female',
    imageSrc: '',
    userId: 10,
  },
  {
    name: 'Jack',
    breed: 'Ibizan Hounds',
    age: 2,
    size: 'small',
    sex: 'male',
    imageSrc: '',
    userId: 11,
  },
  {
    name: 'Bella',
    breed: 'Chinooks',
    age: 1,
    size: 'small',
    sex: 'female',
    imageSrc: '',
    userId: 12,
  },
  {
    name: 'Bear',
    breed: 'Canaan Dogs',
    age: 6,
    size: 'extra-large',
    sex: 'male',
    imageSrc: '',
    userId: 13,
  },
  {
    name: 'Lucy',
    breed: 'Harriers',
    age: 3,
    size: 'medium',
    sex: 'female',
    imageSrc: '',
    userId: 14,
  },
  {
    name: 'Cooper',
    breed: 'Belgian Laekenois',
    age: 5,
    size: 'extra-large',
    sex: 'male',
    imageSrc: '',
    userId: 15,
  },
];

module.exports = pets;
