const pets = [
  {
    name: 'Frank',
    breed: 'French Bulldogs',
    age: 13,
    size: 'extra-large',
    sex: 'female',
    imageSrc: '',
    userId: 1,
  },
  {
    name: 'Rufus',
    breed: 'Samoyed',
    age: 3,
    size: 'large',
    sex: 'male',
    imageSrc: '',
    userId: 2,
  },
  {
    name: 'Buddy',
    breed: 'Golden Retriever',
    age: 5,
    size: 'large',
    sex: 'male',
    imageSrc: '',
    userId: 1,
  },
  {
    name: 'Lola',
    breed: 'Pug',
    age: 7,
    size: 'small',
    sex: 'female',
    imageSrc: '',
    userId: 2,
  },
  {
    name: 'Max',
    breed: 'German Shepherd',
    age: 4,
    size: 'medium',
    sex: 'male',
    imageSrc: '',
    userId: 3,
  },
  {
    name: 'Bailey',
    breed: 'Labrador Retriever',
    age: 2,
    size: 'large',
    sex: 'female',
    imageSrc: '',
    userId: 4,
  },
  {
    name: 'Charlie',
    breed: 'Boxer',
    age: 6,
    size: 'extra-large',
    sex: 'male',
    imageSrc: '',
    userId: 5,
  },
  {
    name: 'Daisy',
    breed: 'Bulldog',
    age: 1,
    size: 'small',
    sex: 'female',
    imageSrc: '',
    userId: 6,
  },
  {
    name: 'Rocky',
    breed: 'Rottweiler',
    age: 9,
    size: 'large',
    sex: 'male',
    imageSrc: '',
    userId: 7,
  },
  {
    name: 'Maggie',
    breed: 'Beagle',
    age: 8,
    size: 'medium',
    sex: 'female',
    imageSrc: '',
    userId: 8,
  },
  {
    name: 'Toby',
    breed: 'Shih Tzu',
    age: 5,
    size: 'small',
    sex: 'male',
    imageSrc: '',
    userId: 9,
  },
  {
    name: 'Molly',
    breed: 'Dalmatian',
    age: 4,
    size: 'medium',
    sex: 'female',
    imageSrc: '',
    userId: 10,
  },
  {
    name: 'Jack',
    breed: 'Chihuahua',
    age: 2,
    size: 'small',
    sex: 'male',
    imageSrc: '',
    userId: 11,
  },
  {
    name: 'Bella',
    breed: 'Yorkshire Terrier',
    age: 1,
    size: 'small',
    sex: 'female',
    imageSrc: '',
    userId: 12,
  },
  {
    name: 'Bear',
    breed: 'Great Dane',
    age: 6,
    size: 'extra-large',
    sex: 'male',
    imageSrc: '',
    userId: 13,
  },
  {
    name: 'Lucy',
    breed: 'Cocker Spaniel',
    age: 3,
    size: 'medium',
    sex: 'female',
    imageSrc: '',
    userId: 14,
  },
  {
    name: 'Cooper',
    breed: 'Bernese Mountain Dog',
    age: 5,
    size: 'extra-large',
    sex: 'male',
    imageSrc: '',
    userId: 15,
  },
];

module.exports = pets;
