const posts = [
  {
    content: `Just adopted a new pup from the NYC animal shelter. Welcome home!`,
    creatorId: 5,
  },
  {
    content: `I love walking my dog through Central Park on sunny days like this!`,
    creatorId: 8,
  },
  {
    content: `I just discovered a new dog-friendly cafe in Brooklyn. So cozy!`,
    creatorId: 14,
  },
  {
    content: `My dog and I just went on a ferry ride to see the Statue of Liberty. So much fun!`,
    creatorId: 7,
  },
  {
    content: `I can't wait for the annual NYC Dog Halloween Parade. My pup's costume is going to be epic!`,
    creatorId: 2,
  },
  {
    content: `I just got back from the West Side Dog Run. It's always a great place to meet other dog owners!`,
    creatorId: 1,
  },
  {
    content: `My dog and I love exploring the dog-friendly shops and cafes in the East Village. So many cute places!`,
    creatorId: 11,
  },
  {
    content: `I just signed up for the NYC Dog Agility Trials. Wish us luck!`,
    creatorId: 19,
  },
  {
    content: `I discovered a new dog-friendly rooftop bar in Manhattan. The views are amazing!`,
    creatorId: 4,
  },
  {
    content: `My dog and I just took a day trip to Coney Island. He loved the beach!`,
    creatorId: 13,
  },
  {
    content: `I just registered my dog for the annual New York City Dog Show. We've been practicing for months!`,
    creatorId: 17,
  },
  {
    content: `I just discovered a new dog park in Queens. It's huge and has lots of amenities!`,
    creatorId: 9,
  },
  {
    content: `I'm so excited to take my dog to the NYC Dog Film Festival next weekend. We love watching movies together!`,
    creatorId: 6,
  },
  {
    content: `My dog and I just went on a tour of some of the famous dog statues around NYC. It was a blast!`,
    creatorId: 12,
  },
  {
    content: `I just signed up for a dog-friendly cooking class in Chelsea. Can't wait to learn some new recipes!`,
    creatorId: 15,
  },
  {
    content: `My dog and I love going on morning runs along the Hudson River. The view is always beautiful!`,
    creatorId: 3,
  },
  {
    content: `I just discovered a new dog-friendly bookstore in Brooklyn. They have a great selection of dog books!`,
    creatorId: 20,
  },
  {
    content: `My dog and I just took a sunset cruise around Manhattan. The city skyline is stunning!`,
    creatorId: 10,
  },
  {
    content: `I'm so excited to attend the annual New York City Dog Expo next month. There will be so many fun activities!`,
    creatorId: 18,
  },
  {
    content: `I just signed up for a dog yoga class in Midtown. It's going to be a great workout for both of us!`,
    creatorId: 16,
  },
];

const postComments = [];

const postLikes = [
  { userId: 29, postId: 88 },
  { userId: 41, postId: 73 },
  { userId: 36, postId: 35 },

  { userId: 26, postId: 29 },
  { userId: 3, postId: 20 },
  { userId: 3, postId: 84 },
  { userId: 44, postId: 60 },
  { userId: 37, postId: 57 },
  { userId: 41, postId: 71 },
  { userId: 27, postId: 30 },
  { userId: 7, postId: 18 },
  { userId: 50, postId: 52 },
  { userId: 6, postId: 57 },
  { userId: 12, postId: 50 },
  { userId: 30, postId: 87 },
  { userId: 20, postId: 31 },
  { userId: 33, postId: 40 },
  { userId: 47, postId: 32 },
  { userId: 36, postId: 72 },
  { userId: 19, postId: 62 },
  { userId: 42, postId: 1 },
  { userId: 4, postId: 36 },
  { userId: 23, postId: 91 },
  { userId: 37, postId: 33 },
  { userId: 28, postId: 86 },
  { userId: 46, postId: 31 },
  { userId: 18, postId: 60 },
  { userId: 13, postId: 86 },
  { userId: 24, postId: 99 },
  { userId: 47, postId: 2 },
  { userId: 6, postId: 10 },
  { userId: 38, postId: 37 },
  { userId: 47, postId: 8 },
  { userId: 22, postId: 33 },
  { userId: 2, postId: 84 },
  { userId: 47, postId: 36 },
  { userId: 35, postId: 94 },
  { userId: 15, postId: 63 },
  { userId: 21, postId: 36 },
  { userId: 11, postId: 13 },
  { userId: 17, postId: 31 },
  { userId: 6, postId: 44 },
  { userId: 29, postId: 89 },
  { userId: 41, postId: 20 },
  { userId: 50, postId: 92 },
  { userId: 48, postId: 29 },
  { userId: 11, postId: 63 },
  { userId: 14, postId: 84 },
  { userId: 25, postId: 94 },
  { userId: 21, postId: 4 },
  { userId: 18, postId: 8 },
  { userId: 1, postId: 48 },
  { userId: 6, postId: 1 },
  { userId: 9, postId: 6 },
  { userId: 35, postId: 38 },
  { userId: 8, postId: 39 },
  { userId: 47, postId: 78 },
  { userId: 46, postId: 30 },
  { userId: 28, postId: 47 },
  { userId: 4, postId: 4 },
  { userId: 40, postId: 19 },
  { userId: 13, postId: 89 },
  { userId: 33, postId: 57 },
  { userId: 26, postId: 66 },
  { userId: 48, postId: 34 },
  { userId: 12, postId: 87 },
  { userId: 42, postId: 5 },
  { userId: 41, postId: 79 },
  { userId: 36, postId: 69 },
  { userId: 10, postId: 63 },
  { userId: 21, postId: 67 },
  { userId: 44, postId: 71 },
  { userId: 27, postId: 62 },
  { userId: 44, postId: 17 },
  { userId: 34, postId: 68 },
  { userId: 15, postId: 65 },
  { userId: 35, postId: 70 },
  { userId: 15, postId: 53 },
  { userId: 29, postId: 39 },
  { userId: 49, postId: 58 },
  { userId: 47, postId: 35 },
  { userId: 22, postId: 58 },
  { userId: 17, postId: 11 },
  { userId: 21, postId: 99 },
  { userId: 36, postId: 52 },
  { userId: 8, postId: 20 },
  { userId: 17, postId: 36 },
  { userId: 20, postId: 69 },
  { userId: 4, postId: 18 },
  { userId: 22, postId: 7 },
  { userId: 16, postId: 38 },
  { userId: 37, postId: 6 },
  { userId: 19, postId: 40 },
  { userId: 4, postId: 13 },
  { userId: 14, postId: 75 },
  { userId: 49, postId: 61 },
  { userId: 3, postId: 22 },
  { userId: 10, postId: 98 },
  { userId: 45, postId: 78 },
];

const postCommentLikes = [
  { userId: 32, postCommentId: 57 },
  { userId: 42, postCommentId: 58 },
  { userId: 49, postCommentId: 56 },
  { userId: 3, postCommentId: 62 },
  { userId: 50, postCommentId: 5 },
  { userId: 39, postCommentId: 68 },

  { userId: 22, postCommentId: 85 },
  { userId: 28, postCommentId: 58 },
  { userId: 20, postCommentId: 89 },
  { userId: 42, postCommentId: 93 },
  { userId: 10, postCommentId: 48 },
  { userId: 23, postCommentId: 68 },
  { userId: 25, postCommentId: 43 },
  { userId: 33, postCommentId: 67 },
  { userId: 50, postCommentId: 30 },
  { userId: 46, postCommentId: 71 },
  { userId: 33, postCommentId: 72 },
  { userId: 23, postCommentId: 57 },
  { userId: 12, postCommentId: 71 },
  { userId: 25, postCommentId: 3 },
  { userId: 37, postCommentId: 39 },
  { userId: 7, postCommentId: 49 },
  { userId: 49, postCommentId: 76 },
  { userId: 16, postCommentId: 27 },
  { userId: 10, postCommentId: 50 },
  { userId: 22, postCommentId: 97 },
  { userId: 19, postCommentId: 54 },
  { userId: 7, postCommentId: 89 },
  { userId: 48, postCommentId: 23 },
  { userId: 15, postCommentId: 21 },
  { userId: 3, postCommentId: 52 },
  { userId: 15, postCommentId: 68 },
  { userId: 37, postCommentId: 7 },
  { userId: 33, postCommentId: 65 },
  { userId: 1, postCommentId: 49 },
  { userId: 47, postCommentId: 29 },
  { userId: 8, postCommentId: 5 },
  { userId: 22, postCommentId: 70 },
  { userId: 7, postCommentId: 75 },
  { userId: 11, postCommentId: 27 },
  { userId: 3, postCommentId: 71 },
  { userId: 14, postCommentId: 45 },

  { userId: 12, postCommentId: 92 },
  { userId: 16, postCommentId: 85 },
  { userId: 3, postCommentId: 98 },
  { userId: 32, postCommentId: 26 },
  { userId: 30, postCommentId: 98 },
  { userId: 18, postCommentId: 51 },
  { userId: 40, postCommentId: 92 },
  { userId: 19, postCommentId: 95 },
  { userId: 50, postCommentId: 22 },
  { userId: 1, postCommentId: 40 },
  { userId: 3, postCommentId: 59 },
  { userId: 29, postCommentId: 55 },
  { userId: 28, postCommentId: 1 },
  { userId: 24, postCommentId: 79 },
  { userId: 13, postCommentId: 51 },
  { userId: 19, postCommentId: 46 },
  { userId: 12, postCommentId: 55 },

  { userId: 38, postCommentId: 2 },
  { userId: 33, postCommentId: 73 },
  { userId: 11, postCommentId: 33 },
  { userId: 13, postCommentId: 15 },
  { userId: 33, postCommentId: 40 },
  { userId: 32, postCommentId: 97 },
  { userId: 14, postCommentId: 56 },
  { userId: 23, postCommentId: 53 },
  { userId: 32, postCommentId: 35 },
  { userId: 37, postCommentId: 41 },
  { userId: 34, postCommentId: 13 },
  { userId: 27, postCommentId: 92 },
  { userId: 13, postCommentId: 60 },
  { userId: 32, postCommentId: 92 },
  { userId: 23, postCommentId: 93 },
  { userId: 23, postCommentId: 77 },
  { userId: 27, postCommentId: 99 },
  { userId: 21, postCommentId: 2 },
  { userId: 37, postCommentId: 99 },
  { userId: 4, postCommentId: 49 },
  { userId: 47, postCommentId: 17 },
  { userId: 17, postCommentId: 70 },
  { userId: 45, postCommentId: 49 },
  { userId: 18, postCommentId: 52 },
  { userId: 49, postCommentId: 19 },
  { userId: 6, postCommentId: 77 },
  { userId: 26, postCommentId: 40 },
  { userId: 36, postCommentId: 85 },
  { userId: 30, postCommentId: 23 },
  { userId: 23, postCommentId: 17 },
  { userId: 18, postCommentId: 16 },
  { userId: 35, postCommentId: 91 },
  { userId: 49, postCommentId: 60 },
  { userId: 26, postCommentId: 36 },
  { userId: 42, postCommentId: 32 },
  { userId: 30, postCommentId: 30 },
  { userId: 6, postCommentId: 69 },
  { userId: 1, postCommentId: 30 },
];

module.exports = { postComments, posts, postLikes, postCommentLikes };
