const sitterList = [
  {
    rate: 54,
    calendar: 'https://calendly.com/',
    bio: `Experienced pet sitter who ensures furry family members are well taken care of in their owner's absence.`,
    canFoster: true,
    userId: 1,
  },
  {
    rate: 35,
    calendar: 'https://calendly.com/',
    bio: `Passionate about providing top-notch care for furry family members, even in their owner's absence.`,
    canFoster: false,
    userId: 2,
  },
  {
    rate: 46,
    calendar: 'https://calendly.com/',
    bio: `Reliable and caring pet sitter committed to ensuring furry family members are happy, healthy, and loved.`,
    canFoster: true,
    userId: 3,
  },
  {
    rate: 39,
    calendar: 'https://calendly.com/',
    bio: `Trustworthy pet sitter with a genuine love for animals and a keen eye for detail.`,
    canFoster: true,
    userId: 4,
  },
  {
    rate: 40,
    calendar: 'https://calendly.com/',
    bio: `Dependable pet sitter with years of experience providing exceptional care for furry family members.`,
    canFoster: true,
    userId: 5,
  },
  {
    rate: 51,
    calendar: 'https://calendly.com/',
    bio: `Compassionate pet sitter who treats furry family members as if they were their own.`,
    canFoster: true,
    userId: 6,
  },
  {
    rate: 56,
    calendar: 'https://calendly.com/',
    bio: `Dedicated pet sitter who goes above and beyond to ensure furry family members are well-cared for.`,
    canFoster: true,
    userId: 7,
  },
  {
    rate: 47,
    calendar: 'https://calendly.com/',
    bio: `Experienced and reliable pet sitter who understands the importance of quality care for furry family members.`,
    canFoster: true,
    userId: 8,
  },
  {
    rate: 44,
    calendar: 'https://calendly.com/',
    bio: `Pet lover and caretaker who is committed to ensuring furry family members receive the best possible care.`,
    canFoster: true,
    userId: 9,
  },
  {
    rate: 40,
    calendar: 'https://calendly.com/',
    bio: `Attentive and compassionate pet sitter who provides peace of mind to pet owners while they're away.`,
    canFoster: true,
    userId: 10,
  },
  {
    rate: 45,
    calendar: 'https://calendly.com/',
    bio: `Longtime dog parent and pet-sitter experienced with reactive dogs. I understand that reactive dogs require special attention and care, and I am confident in my ability to handle any situation that may arise. I am patient, calm, and understanding, and I always make sure to create a safe and secure environment for all dogs in my care.`,
    canFoster: true,
    userId: 21,
  },
  {
    rate: 55,
    calendar: 'https://calendly.com/',
    bio: `Experienced and compassionate pet sitter who provides a safe and playful home for pets while their humans are away.`,
    canFoster: true,
    userId: 22,
  },
];

module.exports = sitterList;
