const sitterPrefsList = [
  {
    hostAtHome: true,
    atOwnerHouse: true,
    reactive: true,
    puppies: false,
    small: false,
    medium: false,
    large: false,
    extraLarge: true,
    multiplePets: true,
    cats: false,
    disabled: true,
    medication: false,
    sitterId: 1,
  },
  {
    hostAtHome: true,
    atOwnerHouse: false,
    reactive: true,
    puppies: false,
    small: false,
    medium: true,
    large: true,
    extraLarge: true,
    multiplePets: true,
    cats: false,
    disabled: false,
    medication: false,
    sitterId: 2,
  },
  {
    hostAtHome: false,
    atOwnerHouse: true,
    reactive: true,
    puppies: false,
    small: false,
    medium: true,
    large: true,
    extraLarge: true,
    multiplePets: true,
    cats: true,
    disabled: true,
    medication: true,
    sitterId: 3,
  },
  {
    hostAtHome: true,
    atOwnerHouse: true,
    reactive: true,
    puppies: true,
    small: false,
    medium: true,
    large: false,
    extraLarge: true,
    multiplePets: false,
    cats: true,
    disabled: true,
    medication: false,
    sitterId: 4,
  },
  {
    hostAtHome: false,
    atOwnerHouse: false,
    reactive: false,
    puppies: false,
    small: true,
    medium: true,
    large: false,
    extraLarge: true,
    multiplePets: false,
    cats: false,
    disabled: false,
    medication: false,
    sitterId: 5,
  },
  {
    hostAtHome: true,
    atOwnerHouse: false,
    reactive: true,
    puppies: false,
    small: false,
    medium: true,
    large: false,
    extraLarge: false,
    multiplePets: false,
    cats: true,
    disabled: false,
    medication: false,
    sitterId: 6,
  },
  {
    hostAtHome: false,
    atOwnerHouse: false,
    reactive: true,
    puppies: false,
    small: true,
    medium: true,
    large: true,
    extraLarge: true,
    multiplePets: true,
    cats: false,
    disabled: true,
    medication: true,
    sitterId: 7,
  },
  {
    hostAtHome: false,
    atOwnerHouse: false,
    reactive: true,
    puppies: true,
    small: true,
    medium: false,
    large: false,
    extraLarge: false,
    multiplePets: false,
    cats: true,
    disabled: false,
    medication: true,
    sitterId: 8,
  },
  {
    hostAtHome: false,
    atOwnerHouse: true,
    reactive: true,
    puppies: true,
    small: false,
    medium: false,
    large: false,
    extraLarge: true,
    multiplePets: true,
    cats: true,
    disabled: false,
    medication: true,
    sitterId: 9,
  },
  {
    hostAtHome: false,
    atOwnerHouse: true,
    reactive: false,
    puppies: false,
    small: false,
    medium: false,
    large: true,
    extraLarge: true,
    multiplePets: false,
    cats: true,
    disabled: false,
    medication: true,
    sitterId: 10,
  },
  {
    hostAtHome: false,
    atOwnerHouse: true,
    reactive: false,
    puppies: false,
    small: false,
    medium: false,
    large: true,
    extraLarge: true,
    multiplePets: false,
    cats: true,
    disabled: false,
    medication: true,
    sitterId: 11,
  },
];

module.exports = sitterPrefsList;
