const users = [
  {
    firstName: 'Cyrus',
    lastName: 'Sattin',
    email: 'csattin0@shutterfly.com',
    phone: '5717454971',
    address1: '4667 Namekagon Street',
    address2: '7256',
    city: 'Reston',
    state: 'Virginia',
    zip: '22096',
    role: 'user',
    imageSrc: 'http://dummyimage.com/131x100.png/dddddd/000000',
    password: 'b0iasdfsdfDNx',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Oliver',
    lastName: 'Mullally',
    email: 'omullally1@drupal.org',
    phone: '3055833764',
    address1: '8138 Huxley Junction',
    address2: null,
    city: 'Miami',
    state: 'Florida',
    zip: '33185',
    role: 'sitter',
    // imageSrc: null,
    password: '9v8v6pqD5szc',
    totalPets: 6,
    canFoster: true,
  },
  {
    firstName: 'Thomasa',
    lastName: 'Merriment',
    email: 'tmerriment2@wix.com',
    phone: '3184428145',
    address1: '7516 Northfield Junction',
    address2: '4',
    city: 'Alexandria',
    state: 'Louisiana',
    zip: '71307',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/217x100.png/ff4444/ffffff',
    password: 'jfPjlrG0O7Nh',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Griffy',
    lastName: 'Doylend',
    email: 'gdoylend3@wikipedia.org',
    phone: '7185625470',
    address1: '2 Kinsman Hill',
    address2: '27',
    city: 'Flushing',
    state: 'New York',
    zip: '11388',
    role: 'user',
    imageSrc: 'http://dummyimage.com/248x100.png/ff4444/ffffff',
    password: 'CY6asdfsacG2e5N',
    totalPets: 5,
    canFoster: true,
  },
  {
    firstName: 'Ugo',
    lastName: 'Pawlata',
    email: 'upawlata4@dot.gov',
    phone: '7049748941',
    address1: '50853 Weeping Birch Plaza',
    address2: '1',
    city: 'Charlotte',
    state: 'North Carolina',
    zip: '28205',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/230x100.png/dddddd/000000',
    password: '588fasdfsiYDq',
    totalPets: 6,
    canFoster: false,
  },
  {
    firstName: 'Sharla',
    lastName: 'Mabbitt',
    email: 'smabbitt5@ibm.com',
    phone: '2511057085',
    address1: '38 Truax Lane',
    address2: null,
    city: 'Mobile',
    state: 'Alabama',
    zip: '36689',
    role: 'user',
    // imageSrc: null,
    password: 'OtsNBasdfsWV',
    totalPets: 4,
    canFoster: false,
  },
  {
    firstName: 'Zonnya',
    lastName: 'Chappel',
    email: 'zchappel6@storify.com',
    phone: '2298774490',
    address1: '486 Lotheville Center',
    address2: '017',
    city: 'Albany',
    state: 'Georgia',
    zip: '31704',
    role: 'user',
    imageSrc: 'http://dummyimage.com/102x100.png/dddddd/000000',
    password: 'R0wb2T3SYM',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Maire',
    lastName: 'Dauncey',
    email: 'mdauncey7@about.com',
    phone: '7024573199',
    address1: '07 Mayer Court',
    address2: '0',
    city: 'Las Vegas',
    state: 'Nevada',
    zip: '89155',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/235x100.png/ff4444/ffffff',
    password: 'qXQi0SsDybjv',
    totalPets: 9,
    canFoster: true,
  },
  {
    firstName: 'Nichole',
    lastName: 'Melendez',
    email: 'nmelendez8@cafepress.com',
    phone: '2392944003',
    address1: '41859 Oxford Hill',
    address2: '3',
    city: 'Fort Myers',
    state: 'Florida',
    zip: '33906',
    role: 'user',
    imageSrc: 'http://dummyimage.com/198x100.png/cc0000/ffffff',
    password: 'Z0j8fsdfsnf2R',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Carley',
    lastName: 'Siege',
    email: 'csiege9@myspace.com',
    phone: '3172702452',
    address1: '07 Veith Parkway',
    address2: '672',
    city: 'Indianapolis',
    state: 'Indiana',
    zip: '46247',
    role: 'user',
    imageSrc: 'http://dummyimage.com/153x100.png/cc0000/ffffff',
    password: '0pwjggdgsdQLxN',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Amara',
    lastName: 'Fleming',
    email: 'afleminga@gnu.org',
    phone: '3177853232',
    address1: '81498 Pearson Court',
    address2: null,
    city: 'Indianapolis',
    state: 'Indiana',
    zip: '46295',
    role: 'sitter',
    // imageSrc: null,
    password: 'AijsfsdfsdCIMdD',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Barnebas',
    lastName: 'Buscombe',
    email: 'bbuscombeb@xinhuanet.com',
    phone: '7815852959',
    address1: '70832 Lillian Park',
    address2: null,
    city: 'Watertown',
    state: 'Massachusetts',
    zip: '02472',
    role: 'user',
    // imageSrc: null,
    password: 'L4DZfY1o9t',
    totalPets: 2,
    canFoster: true,
  },
  {
    firstName: 'Vittorio',
    lastName: 'Pesic',
    email: 'vpesicc@state.gov',
    phone: '2124653810',
    address1: '79989 Golden Leaf Crossing',
    address2: null,
    city: 'New York City',
    state: 'New York',
    zip: '10090',
    role: 'user',
    // imageSrc: null,
    password: 'VKaA07e5w0n',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Gloriana',
    lastName: 'Bruhnicke',
    email: 'gbruhnicked@fastcompany.com',
    phone: '5157047829',
    address1: '34 Stephen Circle',
    address2: null,
    city: 'Des Moines',
    state: 'Iowa',
    zip: '50362',
    role: 'user',
    // imageSrc: null,
    password: 'W2UOLRZFtiH',
    totalPets: 9,
    canFoster: false,
  },
  {
    firstName: 'Babbie',
    lastName: 'Steynor',
    email: 'bsteynore@vinaora.com',
    phone: '5158705368',
    address1: '67 4th Drive',
    address2: null,
    city: 'Des Moines',
    state: 'Iowa',
    zip: '50335',
    role: 'user',
    // imageSrc: null,
    password: '9yOnOclmlL0X',
    totalPets: 9,
    canFoster: true,
  },
  {
    firstName: 'Frederich',
    lastName: 'Goddard',
    email: 'fgoddardf@ucoz.ru',
    phone: '5186802446',
    address1: '38 Marcy Place',
    address2: null,
    city: 'Schenectady',
    state: 'New York',
    zip: '12305',
    role: 'user',
    // imageSrc: null,
    password: 'xccPhrkAtbU',
    totalPets: 8,
    canFoster: false,
  },
  {
    firstName: 'Geneva',
    lastName: 'Simants',
    email: 'gsimantsg@nyu.edu',
    phone: '7407534544',
    address1: '793 Northland Lane',
    address2: null,
    city: 'Columbus',
    state: 'Ohio',
    zip: '43240',
    role: 'user',
    // imageSrc: null,
    password: 'kSOncQGxOftX',
    totalPets: 8,
    canFoster: false,
  },
  {
    firstName: 'Rosabel',
    lastName: 'Spinley',
    email: 'rspinleyh@icio.us',
    phone: '4021535084',
    address1: '28 Caliangt Park',
    address2: '20517',
    city: 'Omaha',
    state: 'Nebraska',
    zip: '68117',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/131x100.png/dddddd/000000',
    password: 'U0ngsdfsdDEnyt',
    totalPets: 8,
    canFoster: false,
  },
  {
    firstName: 'Luciano',
    lastName: 'Yellop',
    email: 'lyellopi@nationalgeographic.com',
    phone: '8509204058',
    address1: '15 Lotheville Avenue',
    address2: null,
    city: 'Pensacola',
    state: 'Florida',
    zip: '32526',
    role: 'sitter',
    // imageSrc: null,
    password: 'ZEVdkufsdf3d',
    totalPets: 6,
    canFoster: false,
  },
  {
    firstName: 'Efrem',
    lastName: 'Arnal',
    email: 'earnalj@ameblo.jp',
    phone: '6503598530',
    address1: '58 Shopko Hill',
    address2: '01256',
    city: 'Los Angeles',
    state: 'California',
    zip: '90045',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/154x100.png/cc0000/ffffff',
    password: '7oJTRfsadfsA',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Penn',
    lastName: 'Munks',
    email: 'pmunksk@columbia.edu',
    phone: '9182477515',
    address1: '32 Atwood Hill',
    address2: null,
    city: 'Tulsa',
    state: 'Oklahoma',
    zip: '74170',
    role: 'user',
    // imageSrc: null,
    password: '8b43Ejtyhrhz8',
    totalPets: 3,
    canFoster: false,
  },
  {
    firstName: 'Cleve',
    lastName: 'Martill',
    email: 'cmartilll@360.cn',
    phone: '3059263268',
    address1: '914 Miller Park',
    address2: null,
    city: 'Miami',
    state: 'Florida',
    zip: '33185',
    role: 'user',
    // imageSrc: null,
    password: 'fF4T2JDKPaG',
    totalPets: 5,
    canFoster: true,
  },
  {
    firstName: 'Luther',
    lastName: 'Clynman',
    email: 'lclynmanm@yahoo.co.jp',
    phone: '9018780089',
    address1: '4825 Dwight Trail',
    address2: '262',
    city: 'Memphis',
    state: 'Tennessee',
    zip: '38109',
    role: 'user',
    imageSrc: 'http://dummyimage.com/169x100.png/ff4444/ffffff',
    password: 'Ukjthtgh88eWh',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Marietta',
    lastName: 'Gaines',
    email: 'mgainesn@flavors.me',
    phone: '6028294205',
    address1: '9 Lakewood Gardens Center',
    address2: null,
    city: 'Phoenix',
    state: 'Arizona',
    zip: '85035',
    role: 'user',
    // imageSrc: null,
    password: 'E2hfghfAbbKG',
    totalPets: 10,
    canFoster: true,
  },
  {
    firstName: 'Ulrikaumeko',
    lastName: 'Tesmond',
    email: 'utesmondo@baidu.com',
    phone: '8048355641',
    address1: '90913 Pearson Drive',
    address2: '8242',
    city: 'Richmond',
    state: 'Virginia',
    zip: '23225',
    role: 'user',
    imageSrc: 'http://dummyimage.com/171x100.png/cc0000/ffffff',
    password: 'ok8O64Xzta',
    totalPets: 6,
    canFoster: true,
  },
  {
    firstName: 'Suzie',
    lastName: 'Schnitter',
    email: 'sschnitterp@is.gd',
    phone: '8177458564',
    address1: '88612 Lindbergh Avenue',
    address2: '7',
    city: 'Arlington',
    state: 'Texas',
    zip: '76004',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/203x100.png/5fa2dd/ffffff',
    password: 'nxxfhghdfgmDTeR',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Ardis',
    lastName: 'Duran',
    email: 'aduranq@paypal.com',
    phone: '4108603183',
    address1: '02 Jay Road',
    address2: '6501',
    city: 'Baltimore',
    state: 'Maryland',
    zip: '21282',
    role: 'user',
    imageSrc: 'http://dummyimage.com/129x100.png/dddddd/000000',
    password: 'E0H645634qEW3',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Astra',
    lastName: 'Ramel',
    email: 'aramelr@msu.edu',
    phone: '6153569557',
    address1: '638 Brentwood Avenue',
    address2: '090',
    city: 'Nashville',
    state: 'Tennessee',
    zip: '37250',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/234x100.png/dddddd/000000',
    password: 'ik9YCbaZWLHs',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Herrick',
    lastName: 'Engelbrecht',
    email: 'hengelbrechts@studiopress.com',
    phone: '7038631335',
    address1: '13440 Stuart Crossing',
    address2: '13',
    city: 'Washington',
    state: 'District of Columbia',
    zip: '20016',
    role: 'user',
    imageSrc: 'http://dummyimage.com/157x100.png/cc0000/ffffff',
    password: '1GQ1Z87fdhgdf9K',
    totalPets: 6,
    canFoster: false,
  },
  {
    firstName: 'Sadella',
    lastName: 'Lennie',
    email: 'slenniet@state.gov',
    phone: '3042482542',
    address1: '3 American Avenue',
    address2: '6292',
    city: 'Charleston',
    state: 'West Virginia',
    zip: '25362',
    role: 'user',
    imageSrc: 'http://dummyimage.com/104x100.png/5fa2dd/ffffff',
    password: 'ctVd2W4abZu',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Lyssa',
    lastName: 'Kroon',
    email: 'lkroonu@mit.edu',
    phone: '6146932226',
    address1: '1 Vahlen Street',
    address2: null,
    city: 'Columbus',
    state: 'Ohio',
    zip: '43210',
    role: 'user',
    // imageSrc: null,
    password: 'QsuCQP6G4qi',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Currey',
    lastName: 'Michel',
    email: 'cmichelv@privacy.gov.au',
    phone: '7579196862',
    address1: '5230 Heffernan Hill',
    address2: '09263',
    city: 'Chesapeake',
    state: 'Virginia',
    zip: '23324',
    role: 'user',
    imageSrc: 'http://dummyimage.com/128x100.png/cc0000/ffffff',
    password: 'XmMXsgdfsdIP',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Heloise',
    lastName: 'Ninotti',
    email: 'hninottiw@hhs.gov',
    phone: '5045704084',
    address1: '94 Hoffman Circle',
    address2: '6537',
    city: 'New Orleans',
    state: 'Louisiana',
    zip: '70179',
    role: 'user',
    imageSrc: 'http://dummyimage.com/147x100.png/cc0000/ffffff',
    password: 'eLa6AOTcuaj',
    totalPets: 8,
    canFoster: false,
  },
  {
    firstName: 'Annnora',
    lastName: 'Napoli',
    email: 'anapolix@cdbaby.com',
    phone: '7754009816',
    address1: '9 Trailsway Road',
    address2: '94531',
    city: 'Reno',
    state: 'Nevada',
    zip: '89519',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/243x100.png/cc0000/ffffff',
    password: 'Sf7ttp4aQD',
    totalPets: 2,
    canFoster: true,
  },
  {
    firstName: 'Jemmy',
    lastName: 'Stit',
    email: 'jstity@cornell.edu',
    phone: '7142564451',
    address1: '06498 Graceland Court',
    address2: '7259',
    city: 'Irvine',
    state: 'California',
    zip: '92710',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/152x100.png/dddddd/000000',
    password: 'v6lVPRFoBn0',
    totalPets: 4,
    canFoster: false,
  },
  {
    firstName: 'Emmie',
    lastName: 'Monkleigh',
    email: 'emonkleighz@cbc.ca',
    phone: '8289743047',
    address1: '108 Pine View Plaza',
    address2: null,
    city: 'Asheville',
    state: 'North Carolina',
    zip: '28805',
    role: 'user',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'Tctn0CNsRQ',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Theresa',
    lastName: 'Allitt',
    email: 'tallitt10@theatlantic.com',
    phone: '5621263607',
    address1: '1 Anderson Lane',
    address2: '691',
    city: 'Los Angeles',
    state: 'California',
    zip: '90045',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/141x100.png/ff4444/ffffff',
    password: 'y8g0f2DflzM',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Haleigh',
    lastName: 'Calbert',
    email: 'hcalbert11@4shared.com',
    phone: '9492953301',
    address1: '80826 Cambridge Alley',
    address2: '75',
    city: 'Orange',
    state: 'California',
    zip: '92867',
    role: 'user',
    imageSrc: 'http://dummyimage.com/168x100.png/5fa2dd/ffffff',
    password: '1seFwv9rTq7',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Maddie',
    lastName: 'Beadham',
    email: 'mbeadham12@ft.com',
    phone: '5179085509',
    address1: '1173 Luster Point',
    address2: '4',
    city: 'Lansing',
    state: 'Michigan',
    zip: '48919',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/124x100.png/cc0000/ffffff',
    password: '75gehfgds37i4J',
    totalPets: 4,
    canFoster: false,
  },
  {
    firstName: 'Felix',
    lastName: 'Chawkley',
    email: 'fchawkley13@spiegel.de',
    phone: '8586739255',
    address1: '0410 Raven Junction',
    address2: null,
    city: 'San Francisco',
    state: 'California',
    zip: '94121',
    role: 'user',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'HmDVSbw0LZ',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Aldwin',
    lastName: 'Wannes',
    email: 'awannes14@umn.edu',
    phone: '7048457169',
    address1: '55 Schlimgen Junction',
    address2: null,
    city: 'Charlotte',
    state: 'North Carolina',
    zip: '28235',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'iIfhgfdsrUR9l',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Leeland',
    lastName: 'Esh',
    email: 'lesh15@nasa.gov',
    phone: '2177590186',
    address1: '61069 Barnett Avenue',
    address2: null,
    city: 'Springfield',
    state: 'Illinois',
    zip: '62718',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'w9ZHEgegdfsdfsfP',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Chelsae',
    lastName: 'Cox',
    email: 'ccox16@ow.ly',
    phone: '2021721220',
    address1: '4 Holy Cross Way',
    address2: '2',
    city: 'Washington',
    state: 'District of Columbia',
    zip: '20503',
    role: 'user',
    imageSrc: 'http://dummyimage.com/139x100.png/5fa2dd/ffffff',
    password: 'z0oUgigdsffKY',
    totalPets: 10,
    canFoster: false,
  },
  {
    firstName: 'Cyrill',
    lastName: 'Yardley',
    email: 'cyardley17@naver.com',
    phone: '2131406481',
    address1: '2832 Anzinger Crossing',
    address2: '90',
    city: 'Los Angeles',
    state: 'California',
    zip: '90030',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/101x100.png/cc0000/ffffff',
    password: 'ACdvfsdfsd8bRx',
    totalPets: 4,
    canFoster: false,
  },
  {
    firstName: 'Pacorro',
    lastName: 'Stenett',
    email: 'pstenett18@meetup.com',
    phone: '8181049744',
    address1: '317 Comanche Alley',
    address2: '5922',
    city: 'Torrance',
    state: 'California',
    zip: '90510',
    role: 'user',
    imageSrc: 'http://dummyimage.com/180x100.png/ff4444/ffffff',
    password: 'xQNVLgdfsdTp',
    totalPets: 6,
    canFoster: false,
  },
  {
    firstName: 'Sheppard',
    lastName: 'Torel',
    email: 'storel19@psu.edu',
    phone: '4344960029',
    address1: '92213 Warner Plaza',
    address2: '548',
    city: 'Charlottesville',
    state: 'Virginia',
    zip: '22903',
    role: 'user',
    imageSrc: 'http://dummyimage.com/189x100.png/ff4444/ffffff',
    password: 'ZvRGfsdfsdfhR',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Vale',
    lastName: 'Amesbury',
    email: 'vamesbury1a@mit.edu',
    phone: '9725228504',
    address1: '57 Armistice Road',
    address2: '99',
    city: 'Plano',
    state: 'Texas',
    zip: '75074',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/140x100.png/cc0000/ffffff',
    password: 'g3IRBkmT2h',
    totalPets: 9,
    canFoster: true,
  },
  {
    firstName: 'Amalita',
    lastName: 'Calrow',
    email: 'acalrow1b@creativecommons.org',
    phone: '7708499164',
    address1: '59 Grim Lane',
    address2: '57569',
    city: 'Lawrenceville',
    state: 'Georgia',
    zip: '30045',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/227x100.png/dddddd/000000',
    password: 'sizU6aau0RAO',
    totalPets: 10,
    canFoster: true,
  },
  {
    firstName: "D'arcy",
    lastName: 'Brame',
    email: 'dbrame1c@army.mil',
    phone: '3607855851',
    address1: '09140 Judy Center',
    address2: '2',
    city: 'Olympia',
    state: 'Washington',
    zip: '98516',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'AfiAjaLjgI',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Giraldo',
    lastName: 'Wakeford',
    email: 'gwakeford1d@free.fr',
    phone: '6785285002',
    address1: '2097 Homewood Pass',
    address2: null,
    city: 'Gainesville',
    state: 'Georgia',
    zip: '30506',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'aTMfsdfsdW08h',
    totalPets: 1,
    canFoster: false,
  },
];

// const passwordEdit = users.map((user) => {
//   if (user.zip.length < 5) {
//     return user;
//   }
// });

// console.log(passwordEdit);

module.exports = users;
