const users = [
  {
    firstName: 'Cyrus',
    lastName: 'Sattin',
    email: 'csattin0@shutterfly.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/131x100.png/dddddd/000000',
    password: 'b0iasdfsdfDNx',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Oliver',
    lastName: 'Mullally',
    email: 'omullally1@drupal.org',
    role: 'sitter',
    // imageSrc: null,
    password: '9v8v6pqD5szc',
    totalPets: 6,
    canFoster: true,
  },
  {
    firstName: 'Thomasa',
    lastName: 'Merriment',
    email: 'tmerriment2@wix.com',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/217x100.png/ff4444/ffffff',
    password: 'jfPjlrG0O7Nh',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Griffy',
    lastName: 'Doylend',
    email: 'gdoylend3@wikipedia.org',
    role: 'user',
    imageSrc: 'http://dummyimage.com/248x100.png/ff4444/ffffff',
    password: 'CY6asdfsacG2e5N',
    totalPets: 5,
    canFoster: true,
  },
  {
    firstName: 'Ugo',
    lastName: 'Pawlata',
    email: 'upawlata4@dot.gov',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/230x100.png/dddddd/000000',
    password: '588fasdfsiYDq',
    totalPets: 6,
    canFoster: false,
  },
  {
    firstName: 'Sharla',
    lastName: 'Mabbitt',
    email: 'smabbitt5@ibm.com',
    role: 'user',
    // imageSrc: null,
    password: 'OtsNBasdfsWV',
    totalPets: 4,
    canFoster: false,
  },
  {
    firstName: 'Zonnya',
    lastName: 'Chappel',
    email: 'zchappel6@storify.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/102x100.png/dddddd/000000',
    password: 'R0wb2T3SYM',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Maire',
    lastName: 'Dauncey',
    email: 'mdauncey7@about.com',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/235x100.png/ff4444/ffffff',
    password: 'qXQi0SsDybjv',
    totalPets: 9,
    canFoster: true,
  },
  {
    firstName: 'Nichole',
    lastName: 'Melendez',
    email: 'nmelendez8@cafepress.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/198x100.png/cc0000/ffffff',
    password: 'Z0j8fsdfsnf2R',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Carley',
    lastName: 'Siege',
    email: 'csiege9@myspace.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/153x100.png/cc0000/ffffff',
    password: '0pwjggdgsdQLxN',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Amara',
    lastName: 'Fleming',
    email: 'afleminga@gnu.org',
    role: 'sitter',
    // imageSrc: null,
    password: 'AijsfsdfsdCIMdD',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Barnebas',
    lastName: 'Buscombe',
    email: 'bbuscombeb@xinhuanet.com',
    role: 'user',
    // imageSrc: null,
    password: 'L4DZfY1o9t',
    totalPets: 2,
    canFoster: true,
  },
  {
    firstName: 'Vittorio',
    lastName: 'Pesic',
    email: 'vpesicc@state.gov',
    role: 'user',
    // imageSrc: null,
    password: 'VKaA07e5w0n',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Gloriana',
    lastName: 'Bruhnicke',
    email: 'gbruhnicked@fastcompany.com',
    role: 'user',
    // imageSrc: null,
    password: 'W2UOLRZFtiH',
    totalPets: 9,
    canFoster: false,
  },
  {
    firstName: 'Babbie',
    lastName: 'Steynor',
    email: 'bsteynore@vinaora.com',
    role: 'user',
    // imageSrc: null,
    password: '9yOnOclmlL0X',
    totalPets: 9,
    canFoster: true,
  },
  {
    firstName: 'Frederich',
    lastName: 'Goddard',
    email: 'fgoddardf@ucoz.ru',
    role: 'user',
    // imageSrc: null,
    password: 'xccPhrkAtbU',
    totalPets: 8,
    canFoster: false,
  },
  {
    firstName: 'Geneva',
    lastName: 'Simants',
    email: 'gsimantsg@nyu.edu',
    role: 'user',
    // imageSrc: null,
    password: 'kSOncQGxOftX',
    totalPets: 8,
    canFoster: false,
  },
  {
    firstName: 'Rosabel',
    lastName: 'Spinley',
    email: 'rspinleyh@icio.us',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/131x100.png/dddddd/000000',
    password: 'U0ngsdfsdDEnyt',
    totalPets: 8,
    canFoster: false,
  },
  {
    firstName: 'Luciano',
    lastName: 'Yellop',
    email: 'lyellopi@nationalgeographic.com',
    role: 'sitter',
    // imageSrc: null,
    password: 'ZEVdkufsdf3d',
    totalPets: 6,
    canFoster: false,
  },
  {
    firstName: 'Efrem',
    lastName: 'Arnal',
    email: 'earnalj@ameblo.jp',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/154x100.png/cc0000/ffffff',
    password: '7oJTRfsadfsA',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Penn',
    lastName: 'Munks',
    email: 'pmunksk@columbia.edu',
    role: 'user',
    // imageSrc: null,
    password: '8b43Ejtyhrhz8',
    totalPets: 3,
    canFoster: false,
  },
  {
    firstName: 'Cleve',
    lastName: 'Martill',
    email: 'cmartilll@360.cn',
    role: 'user',
    // imageSrc: null,
    password: 'fF4T2JDKPaG',
    totalPets: 5,
    canFoster: true,
  },
  {
    firstName: 'Luther',
    lastName: 'Clynman',
    email: 'lclynmanm@yahoo.co.jp',
    role: 'user',
    imageSrc: 'http://dummyimage.com/169x100.png/ff4444/ffffff',
    password: 'Ukjthtgh88eWh',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Marietta',
    lastName: 'Gaines',
    email: 'mgainesn@flavors.me',
    role: 'user',
    // imageSrc: null,
    password: 'E2hfghfAbbKG',
    totalPets: 10,
    canFoster: true,
  },
  {
    firstName: 'Ulrikaumeko',
    lastName: 'Tesmond',
    email: 'utesmondo@baidu.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/171x100.png/cc0000/ffffff',
    password: 'ok8O64Xzta',
    totalPets: 6,
    canFoster: true,
  },
  {
    firstName: 'Suzie',
    lastName: 'Schnitter',
    email: 'sschnitterp@is.gd',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/203x100.png/5fa2dd/ffffff',
    password: 'nxxfhghdfgmDTeR',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Ardis',
    lastName: 'Duran',
    email: 'aduranq@paypal.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/129x100.png/dddddd/000000',
    password: 'E0H645634qEW3',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Astra',
    lastName: 'Ramel',
    email: 'aramelr@msu.edu',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/234x100.png/dddddd/000000',
    password: 'ik9YCbaZWLHs',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Herrick',
    lastName: 'Engelbrecht',
    email: 'hengelbrechts@studiopress.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/157x100.png/cc0000/ffffff',
    password: '1GQ1Z87fdhgdf9K',
    totalPets: 6,
    canFoster: false,
  },
  {
    firstName: 'Sadella',
    lastName: 'Lennie',
    email: 'slenniet@state.gov',
    role: 'user',
    imageSrc: 'http://dummyimage.com/104x100.png/5fa2dd/ffffff',
    password: 'ctVd2W4abZu',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Lyssa',
    lastName: 'Kroon',
    email: 'lkroonu@mit.edu',
    role: 'user',
    // imageSrc: null,
    password: 'QsuCQP6G4qi',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Currey',
    lastName: 'Michel',
    email: 'cmichelv@privacy.gov.au',
    role: 'user',
    imageSrc: 'http://dummyimage.com/128x100.png/cc0000/ffffff',
    password: 'XmMXsgdfsdIP',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Heloise',
    lastName: 'Ninotti',
    email: 'hninottiw@hhs.gov',
    role: 'user',
    imageSrc: 'http://dummyimage.com/147x100.png/cc0000/ffffff',
    password: 'eLa6AOTcuaj',
    totalPets: 8,
    canFoster: false,
  },
  {
    firstName: 'Annnora',
    lastName: 'Napoli',
    email: 'anapolix@cdbaby.com',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/243x100.png/cc0000/ffffff',
    password: 'Sf7ttp4aQD',
    totalPets: 2,
    canFoster: true,
  },
  {
    firstName: 'Jemmy',
    lastName: 'Stit',
    email: 'jstity@cornell.edu',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/152x100.png/dddddd/000000',
    password: 'v6lVPRFoBn0',
    totalPets: 4,
    canFoster: false,
  },
  {
    firstName: 'Emmie',
    lastName: 'Monkleigh',
    email: 'emonkleighz@cbc.ca',
    role: 'user',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'Tctn0CNsRQ',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Theresa',
    lastName: 'Allitt',
    email: 'tallitt10@theatlantic.com',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/141x100.png/ff4444/ffffff',
    password: 'y8g0f2DflzM',
    totalPets: 7,
    canFoster: false,
  },
  {
    firstName: 'Haleigh',
    lastName: 'Calbert',
    email: 'hcalbert11@4shared.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/168x100.png/5fa2dd/ffffff',
    password: '1seFwv9rTq7',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Maddie',
    lastName: 'Beadham',
    email: 'mbeadham12@ft.com',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/124x100.png/cc0000/ffffff',
    password: '75gehfgds37i4J',
    totalPets: 4,
    canFoster: false,
  },
  {
    firstName: 'Felix',
    lastName: 'Chawkley',
    email: 'fchawkley13@spiegel.de',
    role: 'user',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'HmDVSbw0LZ',
    totalPets: 5,
    canFoster: false,
  },
  {
    firstName: 'Aldwin',
    lastName: 'Wannes',
    email: 'awannes14@umn.edu',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'iIfhgfdsrUR9l',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Leeland',
    lastName: 'Esh',
    email: 'lesh15@nasa.gov',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'w9ZHEgegdfsdfsfP',
    totalPets: 3,
    canFoster: true,
  },
  {
    firstName: 'Chelsae',
    lastName: 'Cox',
    email: 'ccox16@ow.ly',
    role: 'user',
    imageSrc: 'http://dummyimage.com/139x100.png/5fa2dd/ffffff',
    password: 'z0oUgigdsffKY',
    totalPets: 10,
    canFoster: false,
  },
  {
    firstName: 'Cyrill',
    lastName: 'Yardley',
    email: 'cyardley17@naver.com',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/101x100.png/cc0000/ffffff',
    password: 'ACdvfsdfsd8bRx',
    totalPets: 4,
    canFoster: false,
  },
  {
    firstName: 'Pacorro',
    lastName: 'Stenett',
    email: 'pstenett18@meetup.com',
    role: 'user',
    imageSrc: 'http://dummyimage.com/180x100.png/ff4444/ffffff',
    password: 'xQNVLgdfsdTp',
    totalPets: 6,
    canFoster: false,
  },
  {
    firstName: 'Sheppard',
    lastName: 'Torel',
    email: 'storel19@psu.edu',
    role: 'user',
    imageSrc: 'http://dummyimage.com/189x100.png/ff4444/ffffff',
    password: 'ZvRGfsdfsdfhR',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Vale',
    lastName: 'Amesbury',
    email: 'vamesbury1a@mit.edu',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/140x100.png/cc0000/ffffff',
    password: 'g3IRBkmT2h',
    totalPets: 9,
    canFoster: true,
  },
  {
    firstName: 'Amalita',
    lastName: 'Calrow',
    email: 'acalrow1b@creativecommons.org',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/227x100.png/dddddd/000000',
    password: 'sizU6aau0RAO',
    totalPets: 10,
    canFoster: true,
  },
  {
    firstName: "D'arcy",
    lastName: 'Brame',
    email: 'dbrame1c@army.mil',
    role: 'admin',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'AfiAjaLjgI',
    totalPets: 8,
    canFoster: true,
  },
  {
    firstName: 'Giraldo',
    lastName: 'Wakeford',
    email: 'gwakeford1d@free.fr',
    role: 'sitter',
    imageSrc: 'http://dummyimage.com/245x100.png/ff4444/ffffff',
    password: 'aTMfsdfsdW08h',
    totalPets: 1,
    canFoster: false,
  },
];

// const passwordEdit = users.map((user) => {
//   if (user.zip.length < 5) {
//     return user;
//   }
// });

// console.log(passwordEdit);

module.exports = users;
