const users = [
  {
    firstName: 'Michael',
    lastName: 'Garcia',
    email: 'mgarcia@gmail.com',
    phone: '646-555-5678',
    address1: '456 Broadway',
    address2: 'Suite 3A',
    city: 'New York',
    state: 'New York',
    zip: '10003',
    role: 'sitter',
    imageSrc: '',
    password: 'p8Vr5nKsBt6',
    totalPets: 1,
    canFoster: true,
    userName: 'mgarcia',
  },
  {
    firstName: 'Amanda',
    lastName: 'Nguyen',
    email: 'amandan@yahoo.com',
    phone: '917-555-7890',
    address1: '789 Lexington Ave',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10022',
    role: 'sitter',
    imageSrc: '',
    password: 'h7Bc3pLmDf5',
    totalPets: 3,
    canFoster: true,
    userName: 'amandan',
  },
  {
    firstName: 'Nicolette',
    lastName: 'Litchmore',
    email: 'nlitchmore2@bloglovin.com',
    phone: '212-555-0187',
    address1: '42 Henry Street',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10002',
    role: 'sitter',
    imageSrc: '',
    password: 'P4ssw0rd',
    totalPets: 2,
    canFoster: false,
    userName: 'nlitchmore2',
  },
  {
    firstName: 'Andrew',
    lastName: 'Cohen',
    email: 'acohen3@yahoo.com',
    phone: '917-555-1029',
    address1: '645 5th Ave',
    address2: 'Apt 14B',
    city: 'New York',
    state: 'New York',
    zip: '10022',
    role: 'sitter',
    imageSrc: '',
    password: 'password123',
    totalPets: 1,
    canFoster: true,
    userName: 'acohen3',
  },
  {
    firstName: 'Lila',
    lastName: 'Kimber',
    email: 'lkimber5@nytimes.com',
    phone: '917-254-6798',
    address1: '46 Walton Street',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10002',
    role: 'sitter',
    imageSrc: '',
    password: 'nXRk26X9',
    totalPets: 2,
    canFoster: false,
    userName: 'lkimber5',
  },
  {
    firstName: 'Armando',
    lastName: 'Dunlevey',
    email: 'adunlevey6@forbes.com',
    phone: '917-986-4327',
    address1: '11 Sunnyside Drive',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10003',
    role: 'sitter',
    imageSrc: '',
    password: 'VpyHqxS9',
    totalPets: 1,
    canFoster: true,
    userName: 'adunlevey6',
  },
  {
    firstName: 'Talia',
    lastName: 'Garcia',
    email: 'tgarcia4@google.com',
    phone: '718-555-2819',
    address1: '525 W 28th St',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10001',
    role: 'sitter',
    imageSrc: '',
    password: 'letmein',
    totalPets: 3,
    canFoster: true,
    userName: 'tgarcia4',
  },
  {
    firstName: 'Ki',
    lastName: 'Loxston',
    email: 'kloxston7@amazonaws.com',
    phone: '212-854-5016',
    address1: '6480 Hoepker Trail',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10128',
    role: 'sitter',
    imageSrc: '',
    password: 'TifrsVXfYr',
    totalPets: 3,
    canFoster: true,
    userName: 'kloxston7',
  },
  {
    firstName: 'Madonna',
    lastName: 'MacCracken',
    email: 'mmaccracken8@columbia.edu',
    phone: '212-854-5016',
    address1: '75054 Anderson Parkway',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10019',
    role: 'sitter',
    imageSrc: '',
    password: 'UkDY6U4',
    totalPets: 1,
    canFoster: false,
    userName: 'mmaccracken8',
  },
  {
    firstName: 'Geralda',
    lastName: 'McIlvenna',
    email: 'gmcilvenna9@nytimes.com',
    phone: '917-254-6659',
    address1: '1153 Hagan Lane',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10001',
    role: 'sitter',
    imageSrc: '',
    password: 'ew49oIhW8',
    totalPets: 2,
    canFoster: false,
    userName: 'gmcilvenna9',
  },
  {
    firstName: 'Nicholas',
    lastName: 'Wattinham',
    email: 'nwattinhamf@cnbc.com',
    phone: '631-747-4064',
    address1: '573 Fuller Terrace',
    address2: '',
    city: 'Sag Harbor',
    state: 'New York',
    zip: '11963',
    role: 'user',
    imageSrc: '',
    password: 'tZMyIlnL5C',
    totalPets: 2,
    canFoster: false,
    userName: 'nwattinhamf',
  },
  {
    firstName: 'Hannah',
    lastName: 'Maroney',
    email: 'hmaroneyg@wired.com',
    phone: '917-554-2263',
    address1: '3216 Wayridge Street',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10016',
    role: 'user',
    imageSrc: '',
    password: '8OyBpjvEQp',
    totalPets: 1,
    canFoster: true,
    userName: 'hmaroneyg',
  },
  {
    firstName: 'Carrie',
    lastName: 'Pincott',
    email: 'cpincotth@yelp.com',
    phone: '718-614-5561',
    address1: '48 Golden Leaf Point',
    address2: '',
    city: 'Brooklyn',
    state: 'New York',
    zip: '11220',
    role: 'user',
    imageSrc: '',
    password: 'H4Ez4sJSfj',
    totalPets: 2,
    canFoster: true,
    userName: 'cpincotth',
  },
  {
    firstName: 'Dylan',
    lastName: 'Goldingham',
    email: 'dgoldinghami@usatoday.com',
    phone: '212-627-5716',
    address1: '9656 Autumn Leaf Plaza',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10150',
    role: 'user',
    imageSrc: '',
    password: 'gmzGkgptbKJx',
    totalPets: 1,
    canFoster: false,
    userName: 'dgoldinghami',
  },
  {
    firstName: 'Linda',
    lastName: 'Butler',
    email: 'lbutlerj@techcrunch.com',
    phone: '646-759-7738',
    address1: '99785 Dixon Court',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10048',
    role: 'user',
    imageSrc: '',
    password: 'nLKp7opCl',
    totalPets: 3,
    canFoster: true,
    userName: 'lbutlerj',
  },
  {
    firstName: 'Zachary',
    lastName: 'Fulford',
    email: 'zfulfordk@businessweek.com',
    phone: '516-541-3186',
    address1: '9 Marcy Drive',
    address2: '',
    city: 'Hempstead',
    state: 'New York',
    zip: '11550',
    role: 'user',
    imageSrc: '',
    password: 'cvG2btxeRs',
    totalPets: 2,
    canFoster: true,
    userName: 'zfulfordk',
  },
  {
    firstName: 'Darius',
    lastName: 'Cazin',
    email: 'dcazin6@outlook.com',
    phone: '212-555-0178',
    address1: '1431 5th Ave',
    address2: '',
    city: 'New York',
    state: 'New York',
    zip: '10029',
    role: 'user',
    imageSrc: '',
    password: 'pL47Jz9bYkw',
    totalPets: 2,
    canFoster: false,
    userName: 'dcazin6',
  },
  {
    firstName: 'Isabella',
    lastName: 'Ferrero',
    email: 'iferrero7@gmail.com',
    phone: '718-555-0139',
    address1: '650 West 42nd St',
    address2: 'Apt 1101',
    city: 'New York',
    state: 'New York',
    zip: '10036',
    role: 'user',
    imageSrc: '',
    password: 'E9VKvH8WfjU',
    totalPets: 1,
    canFoster: true,
    userName: 'iferrero7',
  },
  {
    firstName: 'Kevin',
    lastName: 'Liu',
    email: 'kliu8@yahoo.com',
    phone: '917-555-0198',
    address1: '20 Jay St',
    address2: 'Apt 1607',
    city: 'Brooklyn',
    state: 'New York',
    zip: '11201',
    role: 'user',
    imageSrc: '',
    password: '9ZsCgTbJhnL',
    totalPets: 3,
    canFoster: true,
    userName: 'kliu8',
  },
  {
    firstName: 'Lila',
    lastName: 'Ahmed',
    email: 'lahmed9@hotmail.com',
    phone: '718-555-0148',
    address1: '142-20 84th Dr',
    address2: '',
    city: 'Jamaica',
    state: 'New York',
    zip: '11435',
    role: 'user',
    imageSrc: '',
    password: 'zVj2GtWxh4A',
    totalPets: 1,
    canFoster: false,
    userName: 'lahmed9',
  },
];

// const passwordEdit = users.map((user) => {
//   if (user.password.length < 8) {
//     return user.password;
//   }
// });

// console.log(passwordEdit);

module.exports = users;
